# 项目信息
rick:
  # 名称
  name: sa-token test
  # 版本
  version: 1.0

# 开发环境配置
server:
  port: 9999


# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 1800
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 1800
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  500MB
      # 设置总上传的文件大小
      max-request-size:  800MB
  redis:
    # 地址
    host: 127.0.0.1 # 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 连接服务密码默认为空
    password:
    # 数据库索引
    # database: 0
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    # timeout: 30000
    lettuce:
      shutdown-timeout: 0

#mybatis-plus整合配置
mybatis-plus:
  # mapper扫描包
  mapper-package: com.**.**.mapper
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.**.**.domain
  configuration:
    map-underscore-to-camel-case: true

#log配置
logging:
  # 设置logback.xml位置
  config: classpath:logback-spring.xml
#  level:
#    com.xl: debug
#    org.springframework: warn
  file:
    path: D:\logs
